AWSTemplateFormatVersion: "2010-09-09"
Description: "Sample SAM Template for DebuggingExample"
Globals: 
  Function: 
    Timeout: 10
    Tracing: Active
Outputs: 
  DebuggingExampleApi: 
    Description: "API Gateway endpoint URL for Prod stage for Debugging Example function"
    Value: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/DebuggingExample/"
  DebuggingExampleFunction: 
    Description: "Debugging Example Lambda Function ARN"
    Value: DebuggingExampleFunction.Arn
  DebuggingExampleFunctionIamRole: 
    Description: "Implicit IAM Role created for Debugging Example function"
    Value: DebuggingExampleFunctionRole.Arn
Resources: 
  DebuggingExampleFunction: 
    Properties: 
      CodeUri: src/DebuggingExample/bin/Release/netcoreapp2.1/publish
      Environment: 
        Variables: 
          PARAM1: VALUE
      Events: 
        DebuggingExample: 
          Properties: 
            Method: get
            Path: /
          Type: Api
      FunctionName: DebuggingExample
      Handler: "DebuggingExample::DebuggingExample.Functions::Get"
      Runtime: dotnetcore2.1
    Type: "AWS::Serverless::Function"
Transform: "AWS::Serverless-2016-10-31"